### ISSUE TITLE
[Bug]: Fancy Bed block model broken

### ISSUE THREAD

**Issue by Kyuumulo** [terrarium-earth/Handcrafted#59] opened 2023-09-05 06:41 UTC
### Bug Description

Upon placing a Fancy Bed on the ground, all that shows is two of it's respective plank, along with the actual model attempting to clip through the planks

### Version

2.0.6

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

### Logs or additional context

Latest version for 1.19.2, I'm unsure if that constitutes the "Latest version" check

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment] 2023-09-05 06:44
Duplicate of 
https://github.com/terrarium-earth/Handcrafted/issues/1
https://github.com/terrarium-earth/Handcrafted/issues/31

Issue for most people was either having a block entity optimization mod installed or the better beds mod installed.
I'll see if I can add compat for them but for now you'll have to remove them

**Closed as not planned by AlexNijjar** 2023-09-05 06:44 UTC
Labels: bug, duplicate
